
--------------------------------------------------------------------------------------------------
The C compilation process @ https://codeforwin.org/2017/08/c-compilation-process.html

#> gcc -save-temps compilation.c -o compilation

Generated Files:
1: - compilation.i   (Generated by pre-processor)
    - After the pre-processing of a C program, a ".i" file is generated which is passed to the compiler for compilation. 
2: - compilation.s   (Generated by compiler)
3: - compilation.o   (Generated by assembler)
4: - compilation     (On Linux Generated by linker) or (compilation.exe On Windows)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Phase of Compilation:
The Four Stages of Compiling a C Program @ https://www.calleerlandsson.com/the-four-stages-of-compiling-a-c-program/
Compiling a C program:- Behind the Scenes @ https://www.geeksforgeeks.org/compiling-a-c-program-behind-the-scenes/


--------------------------------------------------------------------------------------------------


