The C compilation process @ https://codeforwin.org/2017/08/c-compilation-process.html

#> gcc -save-temps compilation.c -o compilation

- compilation.i   (Generated by pre-processor)
    - After the pre-processing of a C program, a ".i" file is generated which is passed to the compiler for compilation. 
- compilation.s   (Generated by compiler)
- compilation.o   (Generated by assembler)
- compilation     (On Linux Generated by linker) or (compilation.exe On Windows)


